services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
      # Select build stage dynamically (dev or prod, defaults to dev)
      target: ${BUILD_TARGET:-dev}
    container_name: ${CONTAINER_NAME_WEB}
    working_dir: /app
    ports:
      # Map host and container ports
      - "${HOST_PORT_WEB}:${SERVICE_PORT_WEB}"
    environment:
      # Pass runtime environment variables
      - SERVICE_PORT_WEB=${SERVICE_PORT_WEB}
      - NODE_ENV=${NODE_ENV:-development}
      # Run entrypoint script (ensure executable permissions first)
    entrypoint: ["sh", "-c", "chmod +x ./entrypoint.sh && ./entrypoint.sh"]
    profiles:
      - dev
      - prod
